# This configuration file contains global settings that might be used by multiple nodes

optimization:
  number_poses: 1000 # Optimize using N poses
  starting_pose: 15 # Skip the first N received poses
  number_image_pcl_pairs: 100 # Refine using correspondences from N pairs
  skip_initial_calibration: true # Set to true to skip hand-eye calibration and use values below
  initial_calibration:
    tx: -0.02722
    ty: -0.00068
    tz: -0.07292
    qw: 0.4998
    qx: -0.5024
    qy: 0.4976
    qz: -0.5002

cmrnext:
  amount_correspondences: 5 # Percentage of correspondences per pair. Value in [0, 100].
  rotation_threshold: 50 # [Deg] Img-Pcl pairs with an estimated yaw (using LiDAR odometry) above this threshold are not processed.

io:
  cache_folder: "/data/cache"
  path_base: "/data"
  run_name: "debug_v01" # Name of the run. Used to create a folder in PATH_BASE/experiments.
